import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import PWAProvider from "@/components/PWAProvider";
import InstallPrompt from "@/components/InstallPrompt";
import NotificationToggle from "@/components/NotificationToggle";
import TremorSafelist from "@/components/TremorSafelist";
// app/layout.tsx or app/page.tsx

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
    nocache: true,
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background font-sans text-foreground">
        <InstallPrompt />
        <NotificationToggle />
        <PWAProvider />
        <TremorSafelist />
        <Providers>
          {children}
        </Providers>


      </body>
    </html>
  );
}
